// ============================================================
// DESIGN: "Glassmorphism" — Step 2: Telugu Lyrics Generator
// ============================================================
import { useState } from "react";
import { useProject } from "@/contexts/ProjectContext";
import { DEITIES, LYRICS_TEMPLATES, DeityKey } from "@/lib/studioData";
import { ChevronRight, Copy, Check, RefreshCw, FileText, Wand2 } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

const STRUCTURE_GUIDE = `Structure your lyrics as:
[Pallavi] — Main chorus (2–4 lines, repeated)
[Charanam 1] — First verse (4–6 lines)
[Charanam 2] — Second verse (4–6 lines)
[Charanam 3] — Third verse (optional)
[Anupallavi] — Bridge (optional, 2–4 lines)`;

const WRITING_TIPS: Record<DeityKey, string[]> = {
  venkateswara: [
    "Use names: Govinda, Srinivasa, Balaji, Venkatesha, Tirumala Vasa",
    "Reference: Seven hills (Saptagiri), Alipiri steps, Pushkarini lake",
    "Themes: Seeking refuge, divine darshan, removing sins",
    "Emotions: Devotion, surrender, longing for darshan",
  ],
  ganesha: [
    "Use names: Ganapati, Vighneshwara, Lambodara, Ekadanta",
    "Reference: Modak (sweet), mouse vehicle, lotus, broken tusk",
    "Themes: Removing obstacles, new beginnings, wisdom",
    "Emotions: Joy, auspiciousness, celebration",
  ],
  lakshmi: [
    "Use names: Mahalakshmi, Dhanalakshmi, Padmavathi, Kamala",
    "Reference: Pink lotus, gold coins, white elephants, red saree",
    "Themes: Prosperity, abundance, grace, divine mother",
    "Emotions: Reverence, gratitude, seeking blessings",
  ],
  shiva: [
    "Use names: Mahadeva, Shambho, Nataraja, Bholenath, Maheshwara",
    "Reference: Ganga, crescent moon, trident, Nandi, Kailash",
    "Themes: Destruction of ego, cosmic dance, liberation",
    "Emotions: Awe, surrender, mystical devotion",
  ],
};

export default function Step2Lyrics() {
  const { project, setLyrics, setActiveStep, markStepComplete } = useProject();
  const [copied, setCopied] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [customPrompt, setCustomPrompt] = useState("");
  const [theme, setTheme] = useState("");

  // Support both predefined deities and custom deity names
  const deity = DEITIES.find((d) => d.key === project.deity) || 
    (project.deity ? { key: project.deity, name: project.deity, mood: "Custom" } : null);
  const generateLyricsMutation = trpc.generation.generateLyrics.useMutation();

  const loadTemplate = () => {
    if (project.deity) {
      setLyrics(LYRICS_TEMPLATES[project.deity]);
      toast.success("Template loaded — customize it for your song!");
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(project.lyrics);
    setCopied(true);
    toast.success("Lyrics copied to clipboard");
    setTimeout(() => setCopied(false), 2000);
  };

  const handleAIGenerate = async () => {
    if (!project.deity || project.deity.trim().length === 0) {
      toast.error("Please select a deity first");
      return;
    }
    
    // Ensure deity is properly set
    if (!deity) {
      toast.error("Deity not found");
      return;
    }

    setIsGenerating(true);
    try {
      const result = await generateLyricsMutation.mutateAsync({
        deity: project.deity,
        customPrompt: customPrompt || undefined,
        theme: theme || undefined,
        duration: 4,
        language: "telugu",
      });

      if (result.success && result.data) {
        setLyrics(result.data.lyrics);
        toast.success("✨ Lyrics generated by AI!");
        setCustomPrompt("");
        setTheme("");
      } else {
        toast.error(result.error || "Failed to generate lyrics");
      }
    } catch (error) {
      toast.error("AI generation failed. Check your connection.");
      console.error(error);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleContinue = () => {
    if (project.lyrics.trim().length > 20) {
      markStepComplete(2);
      setActiveStep(3);
    } else {
      toast.error("Please write or load some lyrics first");
    }
  };

  const wordCount = project.lyrics.trim().split(/\s+/).filter(Boolean).length;
  const lineCount = project.lyrics.trim().split("\n").filter(Boolean).length;

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "2rem" }}>
      {/* Header */}
      <div>
        <p style={{ fontSize: "0.75rem", fontWeight: "600", letterSpacing: "0.15em", marginBottom: "0.5rem", color: "#00d4ff", textTransform: "uppercase" }}>
          Step 2
        </p>
        <h2 style={{ fontSize: "1.875rem", fontWeight: "700", marginBottom: "0.5rem", fontFamily: "'Space Grotesk', sans-serif", color: "#00d4ff" }}>
          Write Telugu Lyrics
        </h2>
        {deity && (
          <p style={{ fontSize: "0.875rem", color: "rgba(255, 255, 255, 0.6)" }}>
            Composing for <span style={{ color: "#ff006e" }}>{deity.name}</span> — {deity.mood}
          </p>
        )}
      </div>

      {/* Two-column layout: editor + tips */}
      <div style={{ display: "grid", gridTemplateColumns: "2fr 1fr", gap: "1.5rem" }}>
        {/* Lyrics Editor */}
        <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
            <span style={{ fontSize: "0.875rem", fontWeight: "600", color: "#00d4ff", fontFamily: "'Space Grotesk', sans-serif" }}>
              Lyrics Editor
            </span>
            <div style={{ display: "flex", gap: "0.5rem" }}>
              <button
                onClick={handleAIGenerate}
                disabled={isGenerating || !deity}
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: "0.5rem",
                  fontSize: "0.75rem",
                  padding: "0.5rem 1rem",
                  borderRadius: "0.375rem",
                  background: "linear-gradient(135deg, #00d4ff 0%, #ff006e 100%)",
                  color: "#000",
                  border: "none",
                  fontWeight: "600",
                  cursor: "pointer",
                  opacity: isGenerating || !deity ? 0.6 : 1,
                  transition: "all 200ms",
                }}
              >
                <Wand2 size={12} style={{ animation: isGenerating ? "spin 1s linear infinite" : "none" }} />
                {isGenerating ? "Generating..." : "AI Generate"}
              </button>
              <button
                onClick={loadTemplate}
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: "0.5rem",
                  fontSize: "0.75rem",
                  padding: "0.5rem 1rem",
                  borderRadius: "0.375rem",
                  background: "rgba(0, 212, 255, 0.1)",
                  color: "#00d4ff",
                  border: "1px solid rgba(0, 212, 255, 0.3)",
                  fontWeight: "600",
                  cursor: "pointer",
                  transition: "all 200ms",
                }}
              >
                <FileText size={12} />
                Template
              </button>
              <button
                onClick={handleCopy}
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: "0.5rem",
                  fontSize: "0.75rem",
                  padding: "0.5rem 1rem",
                  borderRadius: "0.375rem",
                  background: "rgba(0, 212, 255, 0.1)",
                  color: copied ? "#39ff14" : "#00d4ff",
                  border: "1px solid rgba(0, 212, 255, 0.3)",
                  fontWeight: "600",
                  cursor: "pointer",
                  transition: "all 200ms",
                }}
              >
                {copied ? <Check size={12} /> : <Copy size={12} />}
                {copied ? "Copied!" : "Copy"}
              </button>
            </div>
          </div>

          <textarea
            value={project.lyrics}
            onChange={(e) => setLyrics(e.target.value)}
            placeholder={`Write your Telugu devotional lyrics here...\n\n[Pallavi]\nగోవింద గోవింద...\n\n[Charanam 1]\n...`}
            style={{
              minHeight: "360px",
              padding: "1rem",
              background: "rgba(0, 212, 255, 0.05)",
              border: "1px solid rgba(0, 212, 255, 0.2)",
              borderRadius: "0.5rem",
              color: "#fff",
              fontSize: "0.875rem",
              fontFamily: "'Inter', sans-serif",
              resize: "vertical",
            }}
          />

          <div style={{ display: "flex", gap: "1rem", fontSize: "0.75rem", color: "rgba(255, 255, 255, 0.5)" }}>
            <span>{wordCount} words</span>
            <span>{lineCount} lines</span>
            <span>~{Math.round(wordCount / 40)} min read</span>
          </div>
        </div>

        {/* Tips Panel */}
        <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
          {/* Structure guide */}
          <div style={{ padding: "1rem", background: "rgba(0, 212, 255, 0.08)", border: "1px solid rgba(0, 212, 255, 0.2)", borderRadius: "0.5rem", backdropFilter: "blur(10px)" }}>
            <p style={{ fontSize: "0.75rem", fontWeight: "600", marginBottom: "0.75rem", color: "#00d4ff", fontFamily: "'Space Grotesk', sans-serif" }}>
              Song Structure
            </p>
            <pre
              style={{
                fontSize: "0.75rem",
                whiteSpace: "pre-wrap",
                lineHeight: "1.5",
                color: "rgba(255, 255, 255, 0.6)",
                fontFamily: "'Inter', monospace",
              }}
            >
              {STRUCTURE_GUIDE}
            </pre>
          </div>

          {/* AI Generation Options */}
          <div style={{ padding: "1rem", background: "rgba(0, 212, 255, 0.08)", border: "1px solid rgba(0, 212, 255, 0.2)", borderRadius: "0.5rem", backdropFilter: "blur(10px)", display: "flex", flexDirection: "column", gap: "0.75rem" }}>
            <p style={{ fontSize: "0.75rem", fontWeight: "600", color: "#39ff14", fontFamily: "'Space Grotesk', sans-serif" }}>
              ✨ AI Options
            </p>
            <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
              <label style={{ fontSize: "0.75rem", fontWeight: "600", color: "rgba(255, 255, 255, 0.6)" }}>
                Theme
              </label>
              <select
                value={theme}
                onChange={(e) => setTheme(e.target.value)}
                style={{
                  padding: "0.5rem",
                  background: "rgba(0, 212, 255, 0.05)",
                  border: "1px solid rgba(0, 212, 255, 0.2)",
                  borderRadius: "0.375rem",
                  color: "#fff",
                  fontSize: "0.75rem",
                }}
              >
                <option value="">Auto-detect</option>
                <option value="devotion">Devotion</option>
                <option value="gratitude">Gratitude</option>
                <option value="protection">Protection</option>
                <option value="love">Divine Love</option>
              </select>
            </div>
            <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
              <label style={{ fontSize: "0.75rem", fontWeight: "600", color: "rgba(255, 255, 255, 0.6)" }}>
                Custom Direction
              </label>
              <textarea
                value={customPrompt}
                onChange={(e) => setCustomPrompt(e.target.value)}
                placeholder="E.g., 'Focus on pilgrimage'"
                style={{
                  padding: "0.5rem",
                  background: "rgba(0, 212, 255, 0.05)",
                  border: "1px solid rgba(0, 212, 255, 0.2)",
                  borderRadius: "0.375rem",
                  color: "#fff",
                  fontSize: "0.75rem",
                  minHeight: "60px",
                  resize: "vertical",
                }}
              />
            </div>
          </div>

          {/* Deity-specific tips */}
          {deity && project.deity && (
            <div style={{ padding: "1rem", background: "rgba(0, 212, 255, 0.08)", border: "1px solid rgba(0, 212, 255, 0.2)", borderRadius: "0.5rem", backdropFilter: "blur(10px)" }}>
              <p style={{ fontSize: "0.75rem", fontWeight: "600", marginBottom: "0.75rem", color: "#ff006e", fontFamily: "'Space Grotesk', sans-serif" }}>
                {deity.name} Writing Tips
              </p>
              <ul style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
                {(WRITING_TIPS[project.deity as DeityKey] || [
                  `Write devotional lyrics honoring ${project.deity}`,
                  "Use poetic language and metaphors",
                  "Include specific attributes or stories",
                  "Structure with Pallavi (chorus) and Charanams (verses)",
                ]).map((tip: string, i: number) => (
                  <li key={i} style={{ display: "flex", gap: "0.5rem", fontSize: "0.75rem", color: "rgba(255, 255, 255, 0.6)" }}>
                    <span style={{ color: "#ff006e" }}>•</span>
                    {tip}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Telugu keyboard hint */}
          <div style={{ padding: "1rem", background: "rgba(0, 212, 255, 0.08)", border: "1px solid rgba(0, 212, 255, 0.2)", borderRadius: "0.5rem", backdropFilter: "blur(10px)" }}>
            <p style={{ fontSize: "0.75rem", fontWeight: "600", marginBottom: "0.5rem", color: "#00d4ff", fontFamily: "'Space Grotesk', sans-serif" }}>
              Telugu Input Tip
            </p>
            <p style={{ fontSize: "0.75rem", color: "rgba(255, 255, 255, 0.5)" }}>
              Use Google Input Tools or Windows Telugu keyboard. You can also paste lyrics from Google Docs or Word.
            </p>
          </div>
        </div>
      </div>

      {/* Continue */}
      <button
        onClick={handleContinue}
        disabled={project.lyrics.trim().length < 20}
        style={{
          display: "flex",
          alignItems: "center",
          gap: "0.5rem",
          padding: "0.75rem 1.5rem",
          borderRadius: "0.5rem",
          fontWeight: "600",
          fontSize: "0.875rem",
          background: "linear-gradient(135deg, #00d4ff 0%, #ff006e 100%)",
          color: "#000",
          border: "none",
          cursor: "pointer",
          opacity: project.lyrics.trim().length < 20 ? 0.4 : 1,
          transition: "all 200ms",
        }}
      >
        Continue to SUNO Style
        <ChevronRight size={16} />
      </button>

      <style>{`
        @keyframes spin {
          from { transform: rotate(0deg); }
          to { transform: rotate(360deg); }
        }
      `}</style>
    </div>
  );
}
