// ============================================================
// DESIGN: "Digital Sanctum" — Step 9: YouTube Export & Metadata
// ============================================================
import { useState, useEffect } from "react";
import { useProject } from "@/contexts/ProjectContext";
import { DEITIES, generateYouTubeMetadata } from "@/lib/studioData";
import { Copy, Check, Download, Youtube, Tag, FileText, Image } from "lucide-react";
import { toast } from "sonner";

function CopyButton({ text, label }: { text: string; label?: string }) {
  const [copied, setCopied] = useState(false);
  const handleCopy = () => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    toast.success(`${label || "Text"} copied!`);
    setTimeout(() => setCopied(false), 2000);
  };
  return (
    <button
      onClick={handleCopy}
      className="flex items-center gap-1 text-xs px-2.5 py-1 rounded transition-colors"
      style={{
        background: copied ? "oklch(0.72 0.12 75 / 0.15)" : "oklch(0.22 0.018 52)",
        color: copied ? "oklch(0.72 0.12 75)" : "oklch(0.55 0.012 65)",
        border: `1px solid ${copied ? "oklch(0.72 0.12 75 / 0.4)" : "oklch(0.25 0.020 55)"}`,
      }}
    >
      {copied ? <Check size={10} /> : <Copy size={10} />}
      {copied ? "Copied!" : "Copy"}
    </button>
  );
}

const SHORTS_TIPS = [
  "Extract the most visually striking 60 seconds",
  "Use the Pallavi (chorus) section — most memorable",
  "Add large Telugu subtitles (easier to read on mobile)",
  "Use vertical crop (9:16) — 1080×1920",
  "Add trending hashtags: #Shorts #TeluguBhakti #Devotional",
  "Post Shorts 2–3 days before the full video for traction",
];

export default function Step9YouTube() {
  const { project, setYouTubeData, markStepComplete } = useProject();
  const deity = DEITIES.find((d) => d.key === project.deity);

  // Auto-generate metadata on mount if not already set
  useEffect(() => {
    if (deity && !project.youtubeTitle) {
      const meta = generateYouTubeMetadata(project, deity);
      setYouTubeData({
        youtubeTitle: meta.youtubeTitle,
        youtubeDescription: meta.description,
        youtubeTags: meta.tags,
        thumbnailPrompt: meta.thumbnailPrompt,
      });
    }
  }, [deity]);

  const handleRegenerate = () => {
    if (!deity) return;
    const meta = generateYouTubeMetadata(project, deity);
    setYouTubeData({
      youtubeTitle: meta.youtubeTitle,
      youtubeDescription: meta.description,
      youtubeTags: meta.tags,
      thumbnailPrompt: meta.thumbnailPrompt,
    });
    toast.success("YouTube metadata regenerated!");
  };

  const handleDownloadAll = () => {
    const content = `YOUTUBE METADATA EXPORT
=======================
Song: ${project.title}
Deity: ${deity?.name}

TITLE:
${project.youtubeTitle}

DESCRIPTION:
${project.youtubeDescription}

TAGS:
${project.youtubeTags.join(", ")}

THUMBNAIL PROMPT:
${project.thumbnailPrompt}

---
Generated by Telugu Devotional Video Studio
`;
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${project.title || "devotional-video"}-youtube-metadata.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Metadata file downloaded!");
  };

  const handleComplete = () => {
    markStepComplete(8);
    toast.success("🎉 Project complete! Your video is ready for YouTube.", { duration: 5000 });
  };

  return (
    <div className="space-y-5">
      {/* Header */}
      <div>
        <p className="text-xs uppercase tracking-widest mb-1" style={{ color: "oklch(0.65 0.14 65)", fontFamily: "'Cinzel', serif" }}>
          Step 8
        </p>
        <h2 className="text-2xl font-bold mb-2" style={{ fontFamily: "'Cinzel', serif", color: "oklch(0.92 0.018 75)" }}>
          YouTube Export & Metadata
        </h2>
        <p className="text-sm" style={{ color: "oklch(0.60 0.015 68)" }}>
          Your complete YouTube package — title, description, tags, and thumbnail prompt. Copy and paste directly into YouTube Studio.
        </p>
      </div>

      {/* Actions */}
      <div className="flex gap-2 flex-wrap">
        <button
          onClick={handleRegenerate}
          className="text-xs px-3 py-1.5 rounded transition-colors"
          style={{ background: "oklch(0.22 0.018 52)", color: "oklch(0.65 0.015 68)", border: "1px solid oklch(0.28 0.025 58)" }}
        >
          Regenerate All
        </button>
        <button
          onClick={handleDownloadAll}
          className="flex items-center gap-1.5 text-xs px-3 py-1.5 rounded transition-colors"
          style={{ background: "oklch(0.22 0.018 52)", color: "oklch(0.65 0.015 68)", border: "1px solid oklch(0.28 0.025 58)" }}
        >
          <Download size={11} />
          Download .txt
        </button>
      </div>

      <div className="grid grid-cols-2 gap-4">
        {/* Left column */}
        <div className="space-y-4">
          {/* Title */}
          <div className="shrine-panel p-4 space-y-2">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Youtube size={14} style={{ color: "oklch(0.72 0.12 75)" }} />
                <p className="text-xs font-semibold" style={{ color: "oklch(0.72 0.12 75)", fontFamily: "'Cinzel', serif" }}>
                  Video Title
                </p>
              </div>
              <CopyButton text={project.youtubeTitle} label="Title" />
            </div>
            <textarea
              value={project.youtubeTitle}
              onChange={(e) => setYouTubeData({ youtubeTitle: e.target.value })}
              className="sanctum-input text-sm"
              rows={2}
            />
            <p className="text-xs" style={{ color: project.youtubeTitle.length > 100 ? "oklch(0.55 0.22 25)" : "oklch(0.45 0.010 60)" }}>
              {project.youtubeTitle.length}/100 characters
            </p>
          </div>

          {/* Tags */}
          <div className="shrine-panel p-4 space-y-2">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Tag size={14} style={{ color: "oklch(0.72 0.12 75)" }} />
                <p className="text-xs font-semibold" style={{ color: "oklch(0.72 0.12 75)", fontFamily: "'Cinzel', serif" }}>
                  Tags ({project.youtubeTags.length})
                </p>
              </div>
              <CopyButton text={project.youtubeTags.join(", ")} label="Tags" />
            </div>
            <div className="flex flex-wrap gap-1.5 max-h-32 overflow-y-auto">
              {project.youtubeTags.map((tag, i) => (
                <span
                  key={i}
                  className="text-xs px-2 py-0.5 rounded"
                  style={{ background: "oklch(0.22 0.018 52)", color: "oklch(0.65 0.015 68)", border: "1px solid oklch(0.28 0.025 58)" }}
                >
                  {tag}
                </span>
              ))}
            </div>
          </div>

          {/* Thumbnail prompt */}
          <div className="shrine-panel p-4 space-y-2">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Image size={14} style={{ color: "oklch(0.72 0.12 75)" }} />
                <p className="text-xs font-semibold" style={{ color: "oklch(0.72 0.12 75)", fontFamily: "'Cinzel', serif" }}>
                  Thumbnail Prompt
                </p>
              </div>
              <CopyButton text={project.thumbnailPrompt} label="Thumbnail prompt" />
            </div>
            <textarea
              value={project.thumbnailPrompt}
              onChange={(e) => setYouTubeData({ thumbnailPrompt: e.target.value })}
              className="sanctum-input text-xs"
              rows={4}
            />
            <p className="text-xs" style={{ color: "oklch(0.45 0.010 60)" }}>
              Use this in Midjourney, DALL-E, or Grok to generate your thumbnail
            </p>
          </div>
        </div>

        {/* Right column */}
        <div className="space-y-4">
          {/* Description */}
          <div className="shrine-panel p-4 space-y-2">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <FileText size={14} style={{ color: "oklch(0.72 0.12 75)" }} />
                <p className="text-xs font-semibold" style={{ color: "oklch(0.72 0.12 75)", fontFamily: "'Cinzel', serif" }}>
                  Description
                </p>
              </div>
              <CopyButton text={project.youtubeDescription} label="Description" />
            </div>
            <textarea
              value={project.youtubeDescription}
              onChange={(e) => setYouTubeData({ youtubeDescription: e.target.value })}
              className="sanctum-input text-xs"
              rows={14}
              style={{ minHeight: "280px" }}
            />
            <p className="text-xs" style={{ color: "oklch(0.45 0.010 60)" }}>
              {project.youtubeDescription.length} characters
            </p>
          </div>

          {/* Shorts tips */}
          <div className="shrine-panel p-4 space-y-2">
            <p className="text-xs font-semibold" style={{ color: "oklch(0.72 0.12 75)", fontFamily: "'Cinzel', serif" }}>
              YouTube Shorts Tips
            </p>
            {SHORTS_TIPS.map((tip, i) => (
              <div key={i} className="flex items-start gap-2 text-xs" style={{ color: "oklch(0.60 0.015 68)" }}>
                <span style={{ color: "oklch(0.65 0.14 65)" }}>•</span>
                {tip}
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Complete button */}
      <button
        onClick={handleComplete}
        className="w-full flex items-center justify-center gap-3 px-6 py-4 rounded-lg font-bold text-base transition-all duration-200 hover:opacity-90 hover:scale-[1.01]"
        style={{
          background: "linear-gradient(135deg, oklch(0.72 0.12 75), oklch(0.65 0.14 65))",
          color: "oklch(0.12 0.015 55)",
          fontFamily: "'Cinzel', serif",
          boxShadow: "0 4px 24px oklch(0.72 0.12 75 / 0.3)",
        }}
      >
        <Youtube size={20} />
        Mark Project Complete — Ready for YouTube!
      </button>
    </div>
  );
}
