// ============================================================
// DESIGN: "Glassmorphism" — Step 2: Telugu Lyrics & SUNO Style Generator
// ============================================================
import { useState } from "react";
import { useProject } from "@/contexts/ProjectContext";
import { DEITIES, LYRICS_TEMPLATES, DeityKey } from "@/lib/studioData";
import { ChevronRight, Copy, Check, FileText, Wand2, RefreshCw } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

const STRUCTURE_GUIDE = `Structure your lyrics as:
[Pallavi] — Main chorus (2–4 lines, repeated)
[Charanam 1] — First verse (4–6 lines)
[Charanam 2] — Second verse (4–6 lines)
[Charanam 3] — Third verse (optional)
[Anupallavi] — Bridge (optional, 2–4 lines)`;

const WRITING_TIPS: Record<DeityKey, string[]> = {
  venkateswara: [
    "Use names: Govinda, Srinivasa, Balaji, Venkatesha, Tirumala Vasa",
    "Reference: Seven hills (Saptagiri), Alipiri steps, Pushkarini lake",
    "Themes: Seeking refuge, divine darshan, removing sins",
    "Emotions: Devotion, surrender, longing for darshan",
  ],
  ganesha: [
    "Use names: Ganapati, Vighneshwara, Lambodara, Ekadanta",
    "Reference: Modak (sweet), mouse vehicle, lotus, broken tusk",
    "Themes: Removing obstacles, new beginnings, wisdom",
    "Emotions: Joy, auspiciousness, celebration",
  ],
  lakshmi: [
    "Use names: Mahalakshmi, Dhanalakshmi, Padmavathi, Kamala",
    "Reference: Pink lotus, gold coins, white elephants, red saree",
    "Themes: Prosperity, abundance, grace, divine mother",
    "Emotions: Reverence, gratitude, seeking blessings",
  ],
  shiva: [
    "Use names: Mahadeva, Shambho, Nataraja, Bholenath, Maheshwara",
    "Reference: Ganga, crescent moon, trident, Nandi, Kailash",
    "Themes: Destruction of ego, cosmic dance, liberation",
    "Emotions: Awe, surrender, mystical devotion",
  ],
};

export default function Step2Lyrics() {
  const { project, setLyrics, setSunoStyle, setActiveStep, markStepComplete } = useProject();
  const [copied, setCopied] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [customPrompt, setCustomPrompt] = useState("");
  const [theme, setTheme] = useState("");
  const [sunoStyleGenerated, setSunoStyleGenerated] = useState(false);
  const [lyricsLength, setLyricsLength] = useState<"short" | "medium" | "long" | "custom">("medium");
  const [customWordCount, setCustomWordCount] = useState(200);
  const [inputMode, setInputMode] = useState<"ai" | "manual">("ai");

  // Support both predefined deities and custom deity names
  const deity = DEITIES.find((d) => d.key === project.deity) || 
    (project.deity ? { key: project.deity, name: project.deity, mood: "Custom" } : null);
  const generateLyricsMutation = trpc.generation.generateLyrics.useMutation();

  const getLyricsDuration = () => {
    switch (lyricsLength) {
      case "short": return 2;
      case "medium": return 4;
      case "long": return 6;
      case "custom": return Math.max(2, Math.min(10, Math.round(customWordCount / 50)));
      default: return 4;
    }
  };

  const loadTemplate = () => {
    if (!deity) {
      toast.error("Please select a deity first");
      return;
    }
    const template = LYRICS_TEMPLATES[deity.key];
    if (template) {
      setLyrics(template);
      toast.success("Template loaded — customize it for your song!");
    } else {
      toast.error("No template available for this deity");
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(project.lyrics);
    setCopied(true);
    toast.success("Lyrics copied to clipboard");
    setTimeout(() => setCopied(false), 2000);
  };

  const handleAIGenerate = async () => {
    if (!project.deity || project.deity.trim().length === 0) {
      toast.error("Please select a deity first");
      return;
    }
    
    if (!deity) {
      toast.error("Deity not found");
      return;
    }

    setIsGenerating(true);
    try {
      const result = await generateLyricsMutation.mutateAsync({
        deity: project.deity,
        customPrompt: customPrompt || undefined,
        theme: theme || undefined,
        duration: getLyricsDuration(),
        language: "telugu",
      });

      if (result.success && result.data) {
        setLyrics(result.data.lyrics);
        
        if (result.data.sunoStyle) {
          setSunoStyle({
            tempo: result.data.sunoStyle.tempo || "medium",
            style: result.data.sunoStyle.style || "Devotional bhajan",
            mood: result.data.sunoStyle.mood || "Meditative & Peaceful",
            instruments: result.data.sunoStyle.instruments || ["Harmonium", "Tabla"],
            vocals: result.data.sunoStyle.vocals || "Male devotional tenor",
          });
          setSunoStyleGenerated(true);
          toast.success("✨ Lyrics and SUNO style generated by AI!");
        } else {
          toast.success("✨ Lyrics generated by AI!");
        }
        setCustomPrompt("");
        setTheme("");
      } else {
        toast.error(result.error || "Failed to generate lyrics");
      }
    } catch (error) {
      toast.error("AI generation failed. Check your connection.");
      console.error(error);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleContinue = () => {
    if (project.lyrics && project.lyrics.trim().length > 20) {
      markStepComplete(2);
      setActiveStep(3);
    } else {
      toast.error("Please write or load some lyrics first");
    }
  };

  const handleSkipToAudio = () => {
    if (project.lyrics && project.lyrics.trim().length > 20) {
      markStepComplete(2);
      markStepComplete(3);
      setActiveStep(4);
    } else {
      toast.error("Please write or load some lyrics first");
    }
  };

  const wordCount = project.lyrics ? project.lyrics.trim().split(/\s+/).filter(Boolean).length : 0;
  const lineCount = project.lyrics ? project.lyrics.trim().split("\n").filter(Boolean).length : 0;

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "2rem" }}>
      {/* Header */}
      <div>
        <p style={{ fontSize: "0.75rem", fontWeight: "600", letterSpacing: "0.15em", marginBottom: "0.5rem", color: "#00d4ff", textTransform: "uppercase" }}>
          Step 2
        </p>
        <h2 style={{ fontSize: "1.875rem", fontWeight: "700", marginBottom: "0.5rem", fontFamily: "'Space Grotesk', sans-serif", color: "#00d4ff" }}>
          Write Telugu Lyrics & SUNO Style
        </h2>
        <p style={{ fontSize: "0.875rem", color: "rgba(255, 255, 255, 0.6)" }}>
          Choose AI generation or manually enter your lyrics. Control the length and get SUNO style suggestions.
        </p>
      </div>

      {/* Input Mode Selector */}
      <div style={{ display: "flex", gap: "0.5rem" }}>
        <button
          onClick={() => setInputMode("ai")}
          style={{
            flex: 1,
            padding: "0.75rem",
            borderRadius: "0.5rem",
            background: inputMode === "ai" ? "linear-gradient(135deg, #00d4ff 0%, #ff006e 100%)" : "rgba(0, 212, 255, 0.1)",
            color: inputMode === "ai" ? "#000" : "#00d4ff",
            border: "1px solid rgba(0, 212, 255, 0.2)",
            fontWeight: "600",
            fontSize: "0.875rem",
            cursor: "pointer",
            transition: "all 200ms",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            gap: "0.5rem",
          }}
        >
          <Wand2 size={16} />
          AI Generate
        </button>
        <button
          onClick={() => setInputMode("manual")}
          style={{
            flex: 1,
            padding: "0.75rem",
            borderRadius: "0.5rem",
            background: inputMode === "manual" ? "linear-gradient(135deg, #00d4ff 0%, #ff006e 100%)" : "rgba(0, 212, 255, 0.1)",
            color: inputMode === "manual" ? "#000" : "#00d4ff",
            border: "1px solid rgba(0, 212, 255, 0.2)",
            fontWeight: "600",
            fontSize: "0.875rem",
            cursor: "pointer",
            transition: "all 200ms",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            gap: "0.5rem",
          }}
        >
          <FileText size={16} />
          Manual Input
        </button>
      </div>

      {/* Two-column layout: editor + tips */}
      <div style={{ display: "grid", gridTemplateColumns: "2fr 1fr", gap: "1.5rem" }}>
        {/* Lyrics Editor */}
        <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
            <span style={{ fontSize: "0.875rem", fontWeight: "600", color: "#00d4ff", fontFamily: "'Space Grotesk', sans-serif" }}>
              Lyrics Editor
            </span>
            <div style={{ display: "flex", gap: "0.5rem" }}>
              {inputMode === "ai" && (
                <button
                  onClick={handleAIGenerate}
                  disabled={isGenerating || !deity}
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: "0.5rem",
                    fontSize: "0.75rem",
                    padding: "0.5rem 1rem",
                    borderRadius: "0.375rem",
                    background: "linear-gradient(135deg, #00d4ff 0%, #ff006e 100%)",
                    color: "#000",
                    border: "none",
                    fontWeight: "600",
                    cursor: "pointer",
                    opacity: isGenerating || !deity ? 0.6 : 1,
                    transition: "all 200ms",
                  }}
                >
                  <Wand2 size={12} style={{ animation: isGenerating ? "spin 1s linear infinite" : "none" }} />
                  {isGenerating ? "Generating..." : "Generate"}
                </button>
              )}
              <button
                onClick={loadTemplate}
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: "0.5rem",
                  fontSize: "0.75rem",
                  padding: "0.5rem 1rem",
                  borderRadius: "0.375rem",
                  background: "rgba(0, 212, 255, 0.1)",
                  color: "#00d4ff",
                  border: "1px solid rgba(0, 212, 255, 0.3)",
                  fontWeight: "600",
                  cursor: "pointer",
                  transition: "all 200ms",
                }}
              >
                <FileText size={12} />
                Template
              </button>
              <button
                onClick={handleCopy}
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: "0.5rem",
                  fontSize: "0.75rem",
                  padding: "0.5rem 1rem",
                  borderRadius: "0.375rem",
                  background: "rgba(0, 212, 255, 0.1)",
                  color: copied ? "#39ff14" : "#00d4ff",
                  border: "1px solid rgba(0, 212, 255, 0.3)",
                  fontWeight: "600",
                  cursor: "pointer",
                  transition: "all 200ms",
                }}
              >
                {copied ? <Check size={12} /> : <Copy size={12} />}
                {copied ? "Copied!" : "Copy"}
              </button>
            </div>
          </div>

          <textarea
            value={project.lyrics}
            onChange={(e) => setLyrics(e.target.value)}
            placeholder={`Write your Telugu devotional lyrics here...\n\n[Pallavi]\nగోవింద గోవింద...\n\n[Charanam 1]\n...`}
            style={{
              minHeight: "360px",
              padding: "1rem",
              background: "rgba(0, 212, 255, 0.05)",
              border: "1px solid rgba(0, 212, 255, 0.2)",
              borderRadius: "0.5rem",
              color: "#fff",
              fontSize: "0.875rem",
              fontFamily: "'Inter', sans-serif",
              resize: "vertical",
            }}
          />

          <div style={{ display: "flex", gap: "1rem", fontSize: "0.75rem", color: "rgba(255, 255, 255, 0.5)" }}>
            <span>{wordCount} words</span>
            <span>{lineCount} lines</span>
            <span>~{Math.round(wordCount / 40)} min read</span>
          </div>

          {/* SUNO Style Display */}
          {sunoStyleGenerated && project.sunoStyle && (
            <div style={{ padding: "1rem", background: "rgba(57, 255, 20, 0.08)", border: "1px solid rgba(57, 255, 20, 0.2)", borderRadius: "0.5rem", backdropFilter: "blur(10px)" }}>
              <p style={{ fontSize: "0.75rem", fontWeight: "600", marginBottom: "0.75rem", color: "#39ff14", fontFamily: "'Space Grotesk', sans-serif" }}>
                ✨ Generated SUNO Style
              </p>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "0.75rem", fontSize: "0.75rem" }}>
                <div>
                  <p style={{ color: "rgba(255, 255, 255, 0.5)" }}>Tempo</p>
                  <p style={{ color: "#39ff14", fontWeight: "600" }}>{project.sunoStyle.tempo}</p>
                </div>
                <div>
                  <p style={{ color: "rgba(255, 255, 255, 0.5)" }}>Mood</p>
                  <p style={{ color: "#39ff14", fontWeight: "600" }}>{project.sunoStyle.mood}</p>
                </div>
                <div>
                  <p style={{ color: "rgba(255, 255, 255, 0.5)" }}>Vocals</p>
                  <p style={{ color: "#39ff14", fontWeight: "600" }}>{project.sunoStyle.vocals}</p>
                </div>
                <div>
                  <p style={{ color: "rgba(255, 255, 255, 0.5)" }}>Instruments</p>
                  <p style={{ color: "#39ff14", fontWeight: "600" }}>{project.sunoStyle.instruments.join(", ")}</p>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Tips Panel */}
        <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
          {inputMode === "ai" && (
            <>
              {/* AI Options */}
              <div style={{ padding: "1rem", background: "rgba(0, 212, 255, 0.08)", border: "1px solid rgba(0, 212, 255, 0.2)", borderRadius: "0.5rem", backdropFilter: "blur(10px)", display: "flex", flexDirection: "column", gap: "0.75rem" }}>
                <p style={{ fontSize: "0.75rem", fontWeight: "600", color: "#39ff14", fontFamily: "'Space Grotesk', sans-serif" }}>
                  ✨ AI Options
                </p>
                
                <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
                  <label style={{ fontSize: "0.75rem", fontWeight: "600", color: "rgba(255, 255, 255, 0.6)" }}>
                    Lyrics Length
                  </label>
                  <select
                    value={lyricsLength}
                    onChange={(e) => setLyricsLength(e.target.value as any)}
                    style={{
                      padding: "0.5rem",
                      background: "rgba(0, 212, 255, 0.05)",
                      border: "1px solid rgba(0, 212, 255, 0.2)",
                      borderRadius: "0.375rem",
                      color: "#fff",
                      fontSize: "0.75rem",
                    }}
                  >
                    <option value="short">Short (2 min)</option>
                    <option value="medium">Medium (4 min)</option>
                    <option value="long">Long (6 min)</option>
                    <option value="custom">Custom</option>
                  </select>
                </div>

                {lyricsLength === "custom" && (
                  <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
                    <label style={{ fontSize: "0.75rem", fontWeight: "600", color: "rgba(255, 255, 255, 0.6)" }}>
                      Word Count: {customWordCount}
                    </label>
                    <input
                      type="range"
                      min="50"
                      max="500"
                      step="10"
                      value={customWordCount}
                      onChange={(e) => setCustomWordCount(parseInt(e.target.value))}
                      style={{ width: "100%", cursor: "pointer" }}
                    />
                  </div>
                )}

                <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
                  <label style={{ fontSize: "0.75rem", fontWeight: "600", color: "rgba(255, 255, 255, 0.6)" }}>
                    Theme
                  </label>
                  <select
                    value={theme}
                    onChange={(e) => setTheme(e.target.value)}
                    style={{
                      padding: "0.5rem",
                      background: "rgba(0, 212, 255, 0.05)",
                      border: "1px solid rgba(0, 212, 255, 0.2)",
                      borderRadius: "0.375rem",
                      color: "#fff",
                      fontSize: "0.75rem",
                    }}
                  >
                    <option value="">Auto-detect</option>
                    <option value="devotion">Devotion</option>
                    <option value="gratitude">Gratitude</option>
                    <option value="protection">Protection</option>
                    <option value="love">Divine Love</option>
                    <option value="wisdom">Wisdom</option>
                  </select>
                </div>

                <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
                  <label style={{ fontSize: "0.75rem", fontWeight: "600", color: "rgba(255, 255, 255, 0.6)" }}>
                    Custom Prompt (Optional)
                  </label>
                  <input
                    type="text"
                    value={customPrompt}
                    onChange={(e) => setCustomPrompt(e.target.value)}
                    placeholder="e.g., 'Add more devotion, slower pace'"
                    style={{
                      padding: "0.5rem",
                      background: "rgba(0, 212, 255, 0.05)",
                      border: "1px solid rgba(0, 212, 255, 0.2)",
                      borderRadius: "0.375rem",
                      color: "#fff",
                      fontSize: "0.75rem",
                    }}
                  />
                </div>
              </div>

              {/* Deity Tips */}
              {deity && WRITING_TIPS[deity.key as DeityKey] && (
                <div style={{ padding: "1rem", background: "rgba(255, 0, 110, 0.08)", border: "1px solid rgba(255, 0, 110, 0.2)", borderRadius: "0.5rem", backdropFilter: "blur(10px)" }}>
                  <p style={{ fontSize: "0.75rem", fontWeight: "600", marginBottom: "0.75rem", color: "#ff006e", fontFamily: "'Space Grotesk', sans-serif" }}>
                    💡 {deity.name} Tips
                  </p>
                  <ul style={{ fontSize: "0.7rem", color: "rgba(255, 255, 255, 0.6)", lineHeight: "1.6", listStylePosition: "inside" }}>
                    {WRITING_TIPS[deity.key as DeityKey].map((tip, i) => (
                      <li key={i} style={{ marginBottom: "0.5rem" }}>
                        {tip}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </>
          )}

          {inputMode === "manual" && (
            <>
              {/* Structure guide */}
              <div style={{ padding: "1rem", background: "rgba(0, 212, 255, 0.08)", border: "1px solid rgba(0, 212, 255, 0.2)", borderRadius: "0.5rem", backdropFilter: "blur(10px)" }}>
                <p style={{ fontSize: "0.75rem", fontWeight: "600", marginBottom: "0.75rem", color: "#00d4ff", fontFamily: "'Space Grotesk', sans-serif" }}>
                  Song Structure
                </p>
                <pre
                  style={{
                    fontSize: "0.7rem",
                    whiteSpace: "pre-wrap",
                    lineHeight: "1.5",
                    color: "rgba(255, 255, 255, 0.6)",
                    fontFamily: "'Inter', monospace",
                  }}
                >
                  {STRUCTURE_GUIDE}
                </pre>
              </div>

              <div style={{ padding: "1rem", background: "rgba(57, 255, 20, 0.08)", border: "1px solid rgba(57, 255, 20, 0.2)", borderRadius: "0.5rem", backdropFilter: "blur(10px)" }}>
                <p style={{ fontSize: "0.75rem", fontWeight: "600", marginBottom: "0.75rem", color: "#39ff14", fontFamily: "'Space Grotesk', sans-serif" }}>
                  💡 Tips
                </p>
                <ul style={{ fontSize: "0.7rem", color: "rgba(255, 255, 255, 0.6)", lineHeight: "1.6", listStylePosition: "inside" }}>
                  <li>• Paste your existing lyrics</li>
                  <li>• Use proper structure</li>
                  <li>• Include deity names</li>
                  <li>• Keep lines singable</li>
                </ul>
              </div>
            </>
          )}
        </div>
      </div>

      {/* Continue Buttons */}
      <div style={{ display: "flex", gap: "1rem" }}>
        <button
          onClick={handleContinue}
          style={{
            flex: 1,
            padding: "0.75rem",
            borderRadius: "0.5rem",
            background: "linear-gradient(135deg, #00d4ff 0%, #ff006e 100%)",
            color: "#000",
            border: "none",
            fontWeight: "600",
            cursor: "pointer",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            gap: "0.5rem",
            transition: "all 200ms",
          }}
        >
          Continue to Audio Upload
          <ChevronRight size={16} />
        </button>
        {sunoStyleGenerated && (
          <button
            onClick={handleSkipToAudio}
            style={{
              flex: 1,
              padding: "0.75rem",
              borderRadius: "0.5rem",
              background: "rgba(57, 255, 20, 0.1)",
              color: "#39ff14",
              border: "1px solid rgba(57, 255, 20, 0.3)",
              fontWeight: "600",
              cursor: "pointer",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              gap: "0.5rem",
              transition: "all 200ms",
            }}
          >
            Skip to Audio Upload
            <ChevronRight size={16} />
          </button>
        )}
      </div>
    </div>
  );
}
